# -*- coding: utf-8 -*-
"""main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MdWryniq3TLdrqB29kl-75RQFKzwjNpy
"""

import barlow

model_dict,model=barlow.getTrainedBarlowModel(250)
print('thats it')

